### ISSUE TITLE
pip install -r requirements.txt会报错

### ISSUE THREAD

**Issue by oschanger** [cyang812/get_tumblr_likes#14]
Invalid requirement: 'requests ~> 2.20.0'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line
    req = Requirement(req)
  File "/Library/Python/2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8], e.msg
InvalidRequirement: Parse error at "u'~> 2.20.'": Expected stringEnd

注释掉后运行ok

**Comment by bluefo** [comment]
https://github.com/cyang812/get_tumblr_likes/issues/3

**Comment by cyang812** [comment]
改了，再试下
