### ISSUE TITLE
获取喜欢列表链接被拒

### ISSUE THREAD

**Issue by Tu-114-s-undercarriage** [cyang812/get_tumblr_likes#5]
如下提示，虽然挂了ssr，但是貌似还是代理出了问题
`
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\get_json_v3.py", line 104, in <module>
    main()
  File ".\get_json_v3.py", line 24, in main
    resp = requests.get(info_url, proxies=PROXIES)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.tumblr.com', port=443): Max retries exceeded with url: /v2/blog/mytheoristtragedy.tumblr.com/info?api_key=mqyfWchrSDffLHqst0k9xLCvsI5JaCyTPJG3ZdCLyQJVm0FX2V (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000215845EB7B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
`

**Comment by cyang812** [comment]
应该是 SSR 的问题。建议换一个版本试试
